Dashboard changes
Deadreyo/software-project pull request #2
Opened 2024-05-12 21:59 UTC by abdlrhman08

- Added total spent
- Transactions get listed on the dashboard page

2024-05-13 08:09 UTC, Deadreyo requested changes

2024-05-13 08:09 UTC, Deadreyo commented on frontend/src/common/LoginController.ts
Guest User logic will fail when the backend is connected. Revert the changes after you finish testing with it.

2024-05-13 08:09 UTC, Deadreyo commented on frontend/src/dashboard/DashboardPageController.ts
> +      return prev + current.getAmount()
Not all transactions are of type "expense". Check the type of the transaction before adding it to `totalSpent`

2024-05-13 15:33 UTC, Deadreyo requested changes

2024-05-13 15:33 UTC, Deadreyo commented on frontend/src/common/LoginController.ts
Remove all the guest user logic. Debug with a normal account.

2024-05-16 16:03 UTC, abdlrhman08 commented on frontend/src/common/LoginController.ts
>          if (!savedUser) {
Adding transactions saves the to the db not to the user, so retrieving the user works only if i get it from the db

2024-05-16 16:45 UTC, Deadreyo requested changes

2024-05-16 16:45 UTC, Deadreyo commented on frontend/src/common/Classes/Transaction.ts
> +  }
Creation date must not be modified, that's why it didn't have a setter. Delete this method and any logic that enables changing it.

2024-05-16 16:45 UTC, Deadreyo commented on frontend/public/dashboard.html
Tables do not refresh after changing a transaction's type.

Example steps:
1- Edit a transaction
2- Change type then close
Observation: Transaction didn't move to the correct table
A quick solution could be to refresh all transactions

2024-05-16 16:45 UTC, Deadreyo commented on frontend/public/dashboard.html
https://github.com/Deadreyo/software-project/assets/52013393/7838755b-0811-4bc8-8983-fb1e12ec5257

What is "Type"? Is it Periodic vs OneTime, or is it Expense vs Income?
It starts as Periodic but changing the category changes it to Expense vs Income.

2024-05-16 16:51 UTC, abdlrhman08 commented on frontend/public/dashboard.html
bro thinks i work a 9 to 5

2024-05-16 18:12 UTC, Deadreyo requested changes

2024-05-16 18:12 UTC, Deadreyo commented on frontend/public/dashboard.html
There should be columns for `date` of OneTime, and `start date` of Periodic. The current Date column reflects `creation date` but it isn't obvious and need to be renamed. Alternatively, you can simply not show the creation date at all.

2024-05-16 18:12 UTC, Deadreyo commented on frontend/public/dashboard.html
![image](https://github.com/Deadreyo/software-project/assets/52013393/528d54d3-d889-4075-8743-778d812b5bb3)

I am trying to edit a Periodic Transaction and periodic fields like `start date`, `interval` and `limit` do not show up to be edited.

2024-05-16 18:12 UTC, Deadreyo commented on frontend/public/dashboard.html
![image](https://github.com/Deadreyo/software-project/assets/52013393/d27e303b-a822-4511-b00c-29eb0b7f8a9e)

For a OneTime Transaction, I expect the `date` field to be edited is to be the date of the transaction. I think it is the set to `creation date`, and changing it doesn't save it.

2024-05-16 18:14 UTC, abdlrhman08 commented on frontend/public/dashboard.html
I like the second option

2024-05-16 20:50 UTC, Deadreyo approved these changes

2024-05-16 20:50 UTC, merged